apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ include "application.namespace" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: "{{ include "secretStore.name" . }}"
    kind: SecretStore
  target:
    name: "{{ include "applicationSecret.name" . }}"
  {{- if .Values.externalSecrets.externalSecret.dataFrom }}
  dataFrom:
  {{- range  .Values.externalSecrets.externalSecret.dataFrom }}
  - extract:
      key: {{ $.Release.Name }}/{{ . }}
  {{- end -}}
{{- end -}}

      