{{- if .Values.externalSecrets.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa-token
  namespace: {{ include "application.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
type: kubernetes.io/service-account-token
{{- end -}}