apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secretStore.name" . }}
  namespace: {{ include "application.namespace" . }}
spec:
  provider:
    vault:
      server: "{{ .Values.externalSecrets.secretStore.providerUrl }}"
      path: "{{ .Values.externalSecrets.secretStore.path }}"
      version: "{{ .Values.externalSecrets.secretStore.version }}"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "{{ .Values.externalSecrets.secretStore.vault.authPath}}"
          # A required field containing the Vault Role to assume.
          role:  {{ .Release.Name }}
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: {{ .Release.Name }}
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          #  used for authenticating with Vault
          secretRef:
            name: "{{ include "serviceAccount.secretName" . }}"
            key: "token"
            namespace: "{{ include "application.namespace" . }}"